<a href="https://colab.research.google.com/github/venkateshgp/weather-Forecast/blob/master/pytorch_linear_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
t1 = torch.tensor(4.)
t2 = torch.tensor([1.,2,3,4])
t3 = torch.tensor([[5.,2],[3,4],[7,9]])
t4 = torch.tensor([[[11,12,13],[13,14,15]],[[15,16,17],[17,18,19]]])


In [3]:
x=torch.tensor(3.)
w=torch.tensor(4., requires_grad=True)
b=torch.tensor(5., requires_grad=True)
y=w*x+b
print(y)

tensor(17., grad_fn=<AddBackward0>)


In [4]:
print(f"dy/dx: {x.grad}")
print(f"dy/dw: {w.grad}")
print(f"dy/db: {b.grad}")

dy/dx: None
dy/dw: None
dy/db: None


In [5]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w.grad)
print(b)


None
tensor([-0.1209,  1.1771], requires_grad=True)


In [6]:
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37]], dtype = 'float32')
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37]], dtype = 'float32')
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [7]:
#MODEL
def model(x):
    return x @ w.t() + b

In [8]:
pred = model(inputs)
# print(pred)

def mse(t1, t2):
  diff = t1 - t2
  return torch.sum(diff * diff) / diff.numel()

loss = mse(pred, targets)
print(loss)
loss.backward()

tensor(9770.2148, grad_fn=<DivBackward0>)


In [9]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [10]:
#Adjust the weights and reset the gradiants
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5
  w.grad.zero_()
  b.grad.zero_()

In [11]:
print(w)
print(b)

tensor([[ 0.2751, -0.0871,  0.5736],
        [-0.1235, -0.3990,  0.0708]], requires_grad=True)
tensor([-0.1209,  1.1771], requires_grad=True)


In [12]:
pred = model(inputs)
# print(pred)

def mse(t1, t2):
  diff = t1 - t2
  return torch.sum(diff * diff) / diff.numel()

loss = mse(pred, targets)
print(loss)
# loss.backward()

tensor(9770.2148, grad_fn=<DivBackward0>)


In [13]:
#Train the model with 100 epochs
for i in range(100):
  pred = model(inputs)
  loss = mse(pred, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [14]:
pred = model(inputs)
loss = mse(pred, targets)
print(loss)
loss.backward()

tensor(194.4196, grad_fn=<DivBackward0>)


In [15]:
print(f"{pred}\n{targets}")

tensor([[ 59.4246,  71.9496],
        [ 82.9256,  96.8569],
        [100.4222, 120.5365],
        [ 44.5735,  59.5592]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.]])


In [16]:
import torch # Make sure torch is imported in this cell as well for clarity

inputs = np.array([[73, 67, 43],[91, 88, 64], [87, 134, 58],[102, 43, 37], [69,96,70],
 [73,67,43],[91,88,64],[87,134,58],[102,43,37],[69,96,70]], dtype='float32')

targets = np.array([[56,70],[81,101],[119,133],[22,37],[103,119],[56,70],[81,101],
 [119,133],[56,70],[81,101]], dtype='float32') # Truncated to 10 rows

# Convert NumPy arrays to PyTorch tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

DATA SETS and LOADERS
Creating **TesorDataSet**
This allows access to 'inputs' and 'targets' as python tuples, which can be used many places with pytorch odules

In [17]:
from torch.utils.data import TensorDataset
print(len(inputs)==len(targets))
#Define datasets
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

True


(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

Now create data loader, which creates batches of input data for targets to process

In [18]:
from torch.utils.data import DataLoader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [19]:
for xb, yb in train_dl:
  print(xb, yb)

tensor([[ 69.,  96.,  70.],
        [102.,  43.,  37.],
        [ 87., 134.,  58.],
        [ 87., 134.,  58.],
        [ 73.,  67.,  43.]]) tensor([[103., 119.],
        [ 22.,  37.],
        [119., 133.],
        [119., 133.],
        [ 56.,  70.]])
tensor([[ 91.,  88.,  64.],
        [ 69.,  96.,  70.],
        [ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.]]) tensor([[ 81., 101.],
        [ 81., 101.],
        [ 81., 101.],
        [ 56.,  70.],
        [ 56.,  70.]])


In [42]:
#Preparing model to handel data
model = torch.nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.4445,  0.2344, -0.5428],
        [-0.1390, -0.1940, -0.0564]], requires_grad=True)
Parameter containing:
tensor([-0.3267,  0.0820], requires_grad=True)


In [43]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.4445,  0.2344, -0.5428],
         [-0.1390, -0.1940, -0.0564]], requires_grad=True),
 Parameter containing:
 tensor([-0.3267,  0.0820], requires_grad=True)]

In [44]:
pred = model(inputs)
loss = mse(pred, targets)
print(pred)
print(loss)

tensor([[-40.4159, -25.4935],
        [-54.8949, -33.2555],
        [-39.0796, -41.2866],
        [-55.6747, -24.5300],
        [-46.4974, -32.0876],
        [-40.4159, -25.4935],
        [-54.8949, -33.2555],
        [-39.0796, -41.2866],
        [-55.6747, -24.5300],
        [-46.4974, -32.0876]], grad_fn=<AddmmBackward0>)
tensor(16545.7617, grad_fn=<DivBackward0>)


<!-- Pytorch built in loss function -->


In [45]:
import torch.nn.functional as F

With using inbuilt loss function "mse_loss" of pytorch, lets find the loss for the current inpputs.

In [46]:
loss_fn = F.mse_loss
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(16545.7617, grad_fn=<MseLossBackward0>)


Loss looks significantly away from main expected values, lets use inbuilt pytorch optimiser function to make this more effeecient.
There are many optimiser function as of let start with 'SGD'.

In [47]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

**Train Ther module**


*   Generate predictions
*   Calculate the loss
*   Adjust the weights by substracting the small quantity proportional to the gradiant
*   Reset the gradiants to the zero

Let us train the data in batches now



In [48]:
#Utility fundction that trains the model
def fit (num_epochs, model, loss_fn, opt):
  for epoch in range(num_epochs):
    for xb, yb in train_dl:
      #Generate prediction
      pred = model(xb)

      #Calculate the loss
      loss = loss_fn(pred, yb)

      #Compute gradiants
      loss.backward()

      #Update the parameters using gradiants
      opt.step()

      #Reset the gradiants to zero
      opt.zero_grad()

   #print the progress
    if (epoch+1) % 10 == 0:
      print('Epoch[{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [49]:
fit(100, model, loss_fn, opt)

Epoch[10/100], Loss: 171.8758
Epoch[20/100], Loss: 41.5859
Epoch[30/100], Loss: 109.6147
Epoch[40/100], Loss: 21.4795
Epoch[50/100], Loss: 149.1324
Epoch[60/100], Loss: 102.4071
Epoch[70/100], Loss: 37.4374
Epoch[80/100], Loss: 38.9439
Epoch[90/100], Loss: 99.4176
Epoch[100/100], Loss: 11.4587


In [50]:
pred = model(inputs)
print(f"INPUTS: {inputs}\n TARGETS: {targets}")

INPUTS: tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
 TARGETS: tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 56.,  70.],
        [ 81., 101.]])
